# Generated by Django 5.0.2 on 2024-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nif', models.CharField(db_column='NIF', max_length=9, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telf', models.CharField(blank=True, max_length=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('km', models.IntegerField(db_column='kM')),
            ],
            options={
                'db_table': 'coche',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50)),
                ('comptador', models.IntegerField()),
            ],
            options={
                'db_table': 'contador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('fecha', models.DateField()),
                ('n_factura', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('base', models.FloatField()),
                ('t_iva', models.FloatField(db_column='t_IVA')),
                ('precio_obra', models.FloatField()),
                ('precio_total', models.FloatField()),
                ('pagado', models.IntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=255)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField(blank=True, null=True)),
                ('cod_fabricante', models.IntegerField(blank=True, null=True)),
                ('precio_total', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'linea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('clasificacion_energetica', models.FloatField(blank=True, db_column='Clasificacion_Energetica', null=True)),
                ('consumo_minimo', models.FloatField(blank=True, db_column='Consumo_Minimo', null=True)),
                ('consumo_maximo', models.FloatField(blank=True, db_column='Consumo_Maximo', null=True)),
                ('emisiones_minimo', models.FloatField(blank=True, db_column='Emisiones_Minimo', null=True)),
                ('emisiones_maximo', models.FloatField(blank=True, db_column='Emisiones_Maximo', null=True)),
            ],
            options={
                'db_table': 'marca_modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('coste', models.FloatField()),
            ],
            options={
                'db_table': 'pack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(db_column='Estado', max_length=1)),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'reparacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoLinea',
            fields=[
                ('tipo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_linea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('login_nombre', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('nif', models.CharField(db_column='NIF', max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
